Download and insert images into snekbox forms
python-discord/kubernetes pull request #155
Opened 2023-07-17 21:54 UTC by ChrisLovering

2023-07-18 09:14 UTC, jchristgit requested changes

2023-07-18 09:21 UTC, ChrisLovering commented on namespaces/default/snekbox-forms/deployment.yaml
> +            wget https://image3.com -O /tmp/img3.png
Sorry, should have raised these as drafts. I'm awaiting the actual image URLs from Kat.

AFAIK `- >` will evaluate each line as a new command, by adding new lines between.

2023-07-18 09:22 UTC, ChrisLovering commented on namespaces/default/snekbox-forms/deployment.yaml
> +          command: ["/bin/sh", "c"]
Yea, that would likely be better (as it would work)

2023-07-28 10:27 UTC, ChrisLovering commented on namespaces/default/snekbox-forms/deployment.yaml
> +            wget https://url.to.file.com/image.png -O /tmp/images/img1.png
This is a placeholder until we decide on the actual image URL that will be used here.

2023-08-11 23:40 UTC, ChrisLovering commented
This is now ready for review. URL to content is redacted until after CJ qualifier

2023-08-12 09:59 UTC, merged