Add Thread Bot
python-discord/kubernetes pull request #68
Opened 2021-08-08 22:07 UTC by ChrisLovering

Adds our thread testing bot, source found here:
https://github.com/python-discord/thread-bot

Currently does nothing, but should be deployable.

2021-08-09 00:10 UTC, jb3 requested changes
Directory should be `thread-bot`, otherwise LGTM.

2021-08-09 00:10 UTC, jb3 requested changes
Oh, also needs an image pull secret.

2021-08-09 08:04 UTC, Akarys42 approved these changes
Lgtm

2021-08-11 19:21 UTC, jb3 approved these changes

2021-08-11 19:23 UTC, merged